#!/usr/bin/env python3
"""
Generate src/lib/data/yearbook.json from the live Supabase roster.

Invariant #12 (INVARIANTS.md): SS2/JSS2 are the priority yearbook
classes each academic year -- not the graduating class (SS3/JSS3, who
belong on the Alumni Almanac once run_promotion() actually graduates
them), and not the newest intake (SS1/JSS1, who this script instead
treats as the priority *stock-photo* source per the same invariant).

This site (tendercare-web) uses adapter-static -- no live Supabase
call ever happens at page-view time, only here, at generation time.
Same shape as tendercare-teacher's sync_students_from_supabase.py:
plain urllib against PostgREST with the anon key, read-only, no SDK.

What this script deliberately does NOT do: invent a quote, ambition,
or any other personal text for a student. Real names, real portrait
links (if a teacher has set one via the roster's Bio/portrait editor),
real class placement -- pulled straight from Supabase. Every student's
`quote` field is always null; the page template renders that as an
honest "not yet supplied" state, never as placeholder prose that
reads like something a real student wrote. See CONTENT_OWNERSHIP.md
and SEPTEMBER-SESSION-WORKFLOW.md's Lane 1 note for why this line
matters more here than almost anywhere else in the codebase.

Usage:
    PUBLIC_SUPABASE_URL=https://your-project.supabase.co \\
    PUBLIC_SUPABASE_ANON_KEY=your-anon-key \\
    python3 generate_yearbook_json.py

    python3 generate_yearbook_json.py --dry-run   # report only, write nothing
"""
import argparse
import json
import os
import sys
import urllib.error
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

OUTPUT_PATH = Path(__file__).parent.parent / "src" / "lib" / "data" / "yearbook.json"

# (stage, level) pairs, not hardcoded class ids -- a class id is a
# human string ('SS2 Science') that a future add_class() call could
# extend (0011_extensible_classes.sql already makes the arm/department
# set open-ended), so filtering by the structured stage/level columns
# is the only version of this query that doesn't quietly miss a class.
PRIORITY_YEARBOOK = [("SS", 2), ("JSS", 2)]
STOCK_PHOTO_SOURCE = [("SS", 1), ("JSS", 1)]


def fetch(supabase_url: str, anon_key: str, path: str) -> list[dict]:
    url = f"{supabase_url}/rest/v1/{path}"
    req = urllib.request.Request(
        url,
        headers={"apikey": anon_key, "Authorization": f"Bearer {anon_key}"},
    )
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            return json.loads(resp.read())
    except urllib.error.HTTPError as e:
        print(f"Supabase request failed ({path}): {e.code} {e.reason}", file=sys.stderr)
        print(e.read().decode(), file=sys.stderr)
        sys.exit(1)


def classes_matching(all_classes: list[dict], pairs: list[tuple[str, int]]) -> list[dict]:
    wanted = set(pairs)
    return [c for c in all_classes if (c["stage"], c["level"]) in wanted]


def build_class_block(cls: dict, students: list[dict]) -> dict:
    roster = [
        {
            "id": s["id"],
            "full_name": s["full_name"],
            "portrait_url": s.get("portrait_url"),
            # Never fabricated -- see module docstring. Populated only if
            # a real per-student quote source exists somewhere and a
            # future revision of this script is pointed at it; until
            # then this stays null and the template shows an honest
            # "not yet supplied" state, not placeholder prose.
            "quote": None,
        }
        for s in students
        if s["class_id"] == cls["id"]
    ]
    return {"class_id": cls["id"], "label": cls.get("label", cls["id"]), "students": roster}


def generate(dry_run: bool = False):
    supabase_url = os.environ.get("PUBLIC_SUPABASE_URL")
    anon_key = os.environ.get("PUBLIC_SUPABASE_ANON_KEY")
    if not supabase_url or not anon_key:
        print("PUBLIC_SUPABASE_URL and PUBLIC_SUPABASE_ANON_KEY must both be set.", file=sys.stderr)
        sys.exit(1)

    all_classes = fetch(supabase_url, anon_key, "classes?select=id,label,stage,level")
    active_students = fetch(
        supabase_url,
        anon_key,
        "students?select=id,full_name,class_id,portrait_url&active=eq.true",
    )

    priority_classes = classes_matching(all_classes, PRIORITY_YEARBOOK)
    stock_classes = classes_matching(all_classes, STOCK_PHOTO_SOURCE)

    data = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "note": (
            "Generated by scripts/generate_yearbook_json.py from the live Supabase "
            "roster. priority_classes are this academic year's SS2/JSS2 cohorts "
            "(invariant #12) -- the ones this yearbook is actually about. "
            "stock_photo_source_classes are SS1/JSS1, the incoming cohorts invariant "
            "#12 designates as the priority source for general site photo use, not "
            "yearbook profiles. Every student's `quote` field is deliberately null -- "
            "never fabricated; see this script's own docstring."
        ),
        "priority_classes": [
            build_class_block(c, active_students) for c in priority_classes
        ],
        "stock_photo_source_classes": [
            build_class_block(c, active_students) for c in stock_classes
        ],
    }

    total_priority = sum(len(c["students"]) for c in data["priority_classes"])
    total_stock = sum(len(c["students"]) for c in data["stock_photo_source_classes"])
    print(
        f"{len(priority_classes)} priority class(es), {total_priority} student(s); "
        f"{len(stock_classes)} stock-photo-source class(es), {total_stock} student(s)."
    )

    if dry_run:
        print("Dry run -- not written.")
        return

    OUTPUT_PATH.write_text(json.dumps(data, indent=2) + "\n")
    print(f"Wrote {OUTPUT_PATH}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--dry-run", action="store_true", help="report what would change, write nothing")
    args = parser.parse_args()
    generate(dry_run=args.dry_run)
